In [84]:
import numpy as np
import pandas as pd

In [3]:
n_trials = nrows = 10000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls = pd.DataFrame(rolls, columns= ['die_1', 'die_2'])
rolls

die_1  die_2
0         5      5
1         5      3
2         4      6
3         5      5
4         6      5
...     ...    ...
9995      5      4
9996      2      1
9997      2      4
9998      3      5
9999      2      1

[10000 rows x 2 columns]

In [4]:
rolls['doubles'] = rolls.die_1 == rolls.die_2
dbl = rolls[rolls.doubles == True].doubles.count()

In [5]:
dbl/len(rolls)*100
# around a 16 percent chance of rolling doubles

16.24

In [6]:
p_heads = .5
n_flips = 8
n_tests = 10 ** 5
flip = np.random.random((n_flips, n_tests))
heads = flip > p_heads
p = (heads.sum(axis = 0) == 3).mean()
p
# 22% chance of 3 exactly

0.21603

In [7]:
p = (heads.sum(axis = 0) >= 3).mean()
p
# 85% chance of 3 or more

0.85582

In [8]:
# Assumptions made for this question:
# 1. There are an equal number of students per cohort
# 2. The selection of students is completly at random

In [9]:
p_data = .25
n_boards = 2
n_tests = 10 ** 5
board = np.random.random((n_boards, n_tests))
ds = p_data >= board
prob = (ds.sum(axis = 0) == 2).mean()
prob
# There is a 6.21% chance that both boards have a data science student on them

0.0633

In [246]:
pop_num = 17
days = 5
n_tests = 10 ** 5
pop_per = np.random.normal(3, 1.5, size = (n_tests, days))
pop_bought = pop_per.sum(axis =1)
pop_yay = (pop_bought < (pop_num - 1)).mean()
pop_per
# 61.95% chance that there are poptarts left

array([[ 2.59280211,  3.51475805, -0.12795263,  4.48907739,  3.87508055],
       [ 2.21771896,  5.7643952 ,  4.39480586,  4.26372508,  4.67200264],
       [-0.07602465,  2.90991238,  2.2085868 ,  3.15992634,  2.01650826],
       ...,
       [ 6.32584527,  0.91073166,  1.51273696,  5.35389114,  4.31581374],
       [ 4.15736275,  3.41519015,  3.73244714,  4.00079969,  5.2677122 ],
       [ 0.92809501, -0.19528921,  0.85642542,  2.2192799 ,  3.58880311]])

In [11]:
m_avg = 178
m_std = 8
f_avg = 170
f_std = 6
m_height = np.random.normal(m_avg, m_std, size = (n_tests,1))
f_height = np.random.normal(f_avg, f_std, size = (n_tests,1))
combo = np.concatenate((m_height, f_height),axis = 1)
height_data = pd.DataFrame(combo, columns = ['male', 'female'])
height_data['rand'] = height_data.female > height_data.male

In [12]:
height_data[height_data['rand'] == 1].rand.sum()/n_tests
# 21.4% chance the woman is taller than the man

0.21086

In [13]:
error = 1/250
n_students = 50
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
perc

0.81619

In [14]:
error = 1/250
n_students = 100
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
perc

0.66958

In [15]:
error = 1/250
n_students = 150
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
perc

0.54453

In [16]:
error = 1/250
n_students = 400
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
perc

0.20123

In [17]:
food = .7
days = 3
n_days = 4
no_food = np.random.random((n_tests, days))
nfts = no_food > food
nft_fails = (nfts.sum(axis = 1) == 3).mean()
nft_fails

0.02649

In [18]:
food_here = np.random.random((n_tests, n_days))
foods = food_here <= food
yay_food = (foods.sum(axis = 1) >= 1).mean()
yay_food

0.99205

In [19]:
.3 * .3 * .3

0.027

In [20]:
n_people = int(23*(23-1)/2)
bday = 1/365
share = np.random.random((n_tests, n_people))
share_chance = share <= bday
bshare = (share_chance.sum(axis = 1) >=1).mean()
bshare

0.50039

In [21]:
75*74

5550

In [297]:
n_people = int(20*(20-1)/2)
bday = 1/365
share = np.random.random((n_tests, n_people))
share_chance = share <= bday
bshare = (share_chance.sum(axis = 1) >=1).mean()
bshare

0.40657

In [44]:
n_people = int(75*(75-1)/2)
bday = 1/365
share = np.random.random((n_tests, n_people))
share_chance = share <= bday
bshare = (share_chance.sum(axis = 1) >=1).mean()
bshare
# 75 people is an almost guaranteed chance that at least 2 people share a bday

0.9996

In [298]:
75*74/2/365

7.602739726027397

In [55]:
area = np.pi*.5**2
area/1

0.7853981633974483

In [54]:
chance = np.random.random((n_tests))
point_chance = area >= chance
overall = point_chance.mean()
overall

0.78418

In [214]:
mage_tests = 10000
h1dice = 6
h2dice = 4

In [238]:
h1 = np.random.choice([1,2,3,4], mage_tests * h1dice).reshape(mage_tests, h1dice)
m1pow = h1.sum(axis = 1)
m1pow

array([11, 12, 13, ..., 11, 16, 20])

In [239]:
h2 = np.random.choice([1,2,3,4,5,6], mage_tests * h2dice).reshape(mage_tests, h2dice)
m2pow = h2.sum(axis = 1)
m2pow

array([10, 11,  8, ..., 18, 13, 12])

In [243]:
big_array = np.concatenate([m1pow,m2pow])
big_array

array([11, 12, 13, ..., 18, 13, 12])

In [217]:
mage_duel = pd.DataFrame([m1pow,m2pow]).T

In [218]:
mage_duel = mage_duel.rename(columns = {0 : 'mage1', 1 : 'mage2'})

In [219]:
mage_duel['duel_result'] = mage_duel.mage1 - mage_duel.mage2

In [220]:
mage_duel

mage1  mage2  duel_result
0        11     14           -3
1        13     17           -4
2        16     12            4
3        16     18           -2
4        14     10            4
...     ...    ...          ...
9995     18     13            5
9996     19     18            1
9997     15     14            1
9998     18      8           10
9999     13      9            4

[10000 rows x 3 columns]

In [221]:
mtie = mage_duel.duel_result == 0
m1w = mage_duel.duel_result > 0
m2w = mage_duel.duel_result < 0

In [225]:
tie = mtie.mean()
m1 = m1w.mean()
m2 = m2w.mean()

In [231]:
print(tie*100,'tie', m1*100,'mage1', m2*100,'mage2')

8.41 tie 54.64 mage1 36.95 mage2


1.0

In [292]:
point = np.random.random((n_tests, 2))
circle = point.sum(axis = 1) <= .5
circle.mean()*4

0.49544