In [1]:
import numpy as np
import pandas as pd

In [2]:
n_trials = nrows = 10000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls = pd.DataFrame(rolls, columns= ['die_1', 'die_2'])
rolls

die_1  die_2
0         2      2
1         6      3
2         4      2
3         4      6
4         3      5
...     ...    ...
9995      2      3
9996      3      4
9997      1      2
9998      5      3
9999      2      4

[10000 rows x 2 columns]

In [3]:
rolls['doubles'] = rolls.die_1 == rolls.die_2
dbl = rolls[rolls.doubles == True].doubles.count()

In [4]:
dbl/len(rolls)*100
# around a 16 percent chance of rolling doubles

16.939999999999998

In [45]:
p_heads = .5
n_flips = 8
n_tests = 10 ** 5
flip = np.random.random((n_flips, n_tests))
heads = flip > p_heads
p = (heads.sum(axis = 0) == 3).mean()
p
# 22% chance of 3 exactly

0.21867

In [6]:
p = (heads.sum(axis = 0) > 3).mean()
p
# 64% chance of more than 3

0.63568

In [7]:
# Assumptions made for this question:
# 1. There are an equal number of students per cohort
# 2. The selection of students is completly at random

In [8]:
p_data = .25
n_boards = 2
n_tests = 10 ** 5
board = np.random.random((n_boards, n_tests))
ds = p_data >= board
prob = (ds.sum(axis = 0) == 2).mean()
prob
# There is around a 6.21% chance that both boards have a data science student on them

0.06155

In [9]:
pop_num = 17
days = 5
n_tests = 10 ** 5
pop_per = np.random.normal(3, 1.5, size = (n_tests, days))
pop_bought = pop_per.sum(axis =1)
pop_yay = (pop_bought < (pop_num - 1)).mean()
pop_yay
# 61.95% chance that there are poptarts left

0.61656

In [10]:
m_avg = 178
m_std = 8
f_avg = 170
f_std = 6
m_height = np.random.normal(m_avg, m_std, size = (n_tests,1))
f_height = np.random.normal(f_avg, f_std, size = (n_tests,1))
combo = np.concatenate((m_height, f_height),axis = 1)
height_data = pd.DataFrame(combo, columns = ['male', 'female'])
height_data['rand'] = height_data.female > height_data.male

# You dont have to merge the arrays or make them into a dataframe to acomplish this

In [11]:
height_data[height_data['rand'] == 1].rand.sum()/n_tests
# 21.4% chance the woman is taller than the man

0.21265

In [12]:
error = 1/250
n_students = 50
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
perc

0.81794

In [13]:
error = 1/250
n_students = 100
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
perc

0.66984

In [14]:
error = 1/250
n_students = 150
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
1-perc

0.45364000000000004

In [15]:
error = 1/250
n_students = 450
tests = np.random.random((n_students, n_tests))
error_chance = tests <= error
perc = (error_chance.sum(axis = 0) == 0).mean()
perc

0.16387

In [16]:
food = .7
days = 3
n_days = 4
no_food = np.random.random((n_tests, days))
nfts = no_food > food
nft_fails = (nfts.sum(axis = 1) == 3).mean()
nft_fails

0.02648

In [17]:
food_here = np.random.random((n_tests, n_days))
foods = food_here <= food
yay_food = (foods.sum(axis = 1) >= 1).mean()
yay_food

0.99179

In [18]:
.3 * .3 * .3

0.027

In [19]:
n_people = int(23*(23-1)/2)
bday = 1/365
share = np.random.random((n_tests, n_people))
share_chance = share <= bday
bshare = (share_chance.sum(axis = 1) >=1).mean()
bshare

0.49983

In [20]:
75*74

5550

In [21]:
n_people = int(20*(20-1)/2)
bday = 1/365
share = np.random.random((n_tests, n_people))
share_chance = share <= bday
bshare = (share_chance.sum(axis = 1) >=1).mean()
bshare

0.40426

In [22]:
n_people = int(75*(75-1)/2)
bday = 1/365
share = np.random.random((n_tests, n_people))
share_chance = share <= bday
bshare = (share_chance.sum(axis = 1) >=1).mean()
bshare
# 75 people is an almost guaranteed chance that at least 2 people share a bday

0.99938

In [23]:
75*74/2/365

7.602739726027397

In [24]:
area = np.pi*.5**2
area/1

0.7853981633974483

In [25]:
chance = np.random.random((n_tests))
point_chance = area >= chance
overall = point_chance.mean()
overall

0.78611

In [26]:
mage_tests = 10000
h1dice = 6
h2dice = 4

In [27]:
h1 = np.random.choice([1,2,3,4], mage_tests * h1dice).reshape(mage_tests, h1dice)
m1pow = h1.sum(axis = 1)
m1pow

array([19, 20, 10, ..., 18, 18, 14])

In [28]:
h2 = np.random.choice([1,2,3,4,5,6], mage_tests * h2dice).reshape(mage_tests, h2dice)
m2pow = h2.sum(axis = 1)
m2pow

array([ 9, 15, 18, ..., 13, 15, 12])

In [29]:
big_array = np.concatenate([m1pow,m2pow])
big_array

array([19, 20, 10, ..., 13, 15, 12])

In [30]:
mage_duel = pd.DataFrame([m1pow,m2pow]).T

In [31]:
mage_duel = mage_duel.rename(columns = {0 : 'mage1', 1 : 'mage2'})

In [32]:
mage_duel['duel_result'] = mage_duel.mage1 - mage_duel.mage2

In [33]:
mage_duel

mage1  mage2  duel_result
0        19      9           10
1        20     15            5
2        10     18           -8
3        15     10            5
4        16     12            4
...     ...    ...          ...
9995     11      9            2
9996     14     14            0
9997     18     13            5
9998     18     15            3
9999     14     12            2

[10000 rows x 3 columns]

In [34]:
mtie = mage_duel.duel_result == 0
m1w = mage_duel.duel_result > 0
m2w = mage_duel.duel_result < 0

In [35]:
tie = mtie.mean()
m1 = m1w.mean()
m2 = m2w.mean()

In [36]:
print(tie*100,'tie', m1*100,'mage1', m2*100,'mage2')

8.540000000000001 tie 54.32 mage1 37.14 mage2


In [37]:
point = np.random.random((n_tests, 2))
circle = point.sum(axis = 1) <= .5
circle.mean()*4

0.49848

In [38]:
pop_num = 17
days = 5
pop_per = np.random.normal(3, 1.5, size = n_tests * 5).astype(int)
pop_df = pd.DataFrame(pop_per)
pop_df = pop_df[pop_df[0] > 0]
new_pop = pop_df.to_numpy().reshape(int(len(pop_df)/days),days)
pop_bought = new_pop.sum(axis = 1)
pop_yay = (pop_bought < (pop_num - 1)).mean()
pop_yay
# Around 71.76% chance that there are poptarts left, this works only one out of every 5 or so tries because it has to
# have a randomly generated array that is evenly divisible by 5 once negatives are removed

ValueError: cannot reshape array of size 454587 into shape (90917,5)

In [40]:
p = .1
n = 618

In [66]:
x = np.random.random((n, n_tests))
success = x <= p
prob = (success.sum(axis = 0) >= 70).mean()
prob

1.0

In [98]:
success = 1/10
n_people = 618
tests = np.random.random((n_people, n_tests))
success_chance = tests <= success
perc = (success_chance.sum(axis = 0) > 69).mean()
perc

0.14995

0.15115